apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/timestamp: '1776872532'
  labels:
    temporal.io/build-id: 19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc-8b6c
    temporal.io/deployment-name: helloworld
  name: helloworld-19ec48c7b3-8e2cfc163e
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      temporal.io/build-id: 19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc-8b6c
      temporal.io/deployment-name: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        deployment.kubernetes.io/timestamp: '1776872532'
        temporal.io/connection-spec-hash: af097712729b400d1c3b970cfd3cdfae3722060f075bcd1633c7a68c0200bbe1
        temporal.io/pod-template-spec-hash: 75eb9926891db98fe5b51d0b823fcf48fea5d8cb90c58e98ce7d436ed67c2843
      labels:
        temporal.io/build-id: 19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc-8b6c
        temporal.io/deployment-name: helloworld
    spec:
      containers:
      - env:
        - name: TEMPORAL_TASK_QUEUE
          value: default/helloworld
        - name: TEMPORAL_ADDRESS
          value: ap-northeast-1.aws.api.temporal.io:7233
        - name: TEMPORAL_NAMESPACE
          value: quickstart-shashwat-learning.x72yu
        - name: TEMPORAL_DEPLOYMENT_NAME
          value: default/helloworld
        - name: TEMPORAL_WORKER_BUILD_ID
          value: 19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc-8b6c
        - name: TEMPORAL_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: temporal-api-key
        image: helloworld:19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc0ca029
        imagePullPolicy: IfNotPresent
        name: main
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rainbow-dashboard
  name: rainbow-dashboard
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rainbow-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-04-21T16:32:46-07:00'
      labels:
        app: rainbow-dashboard
    spec:
      containers:
      - args:
        - --namespace
        - $(NAMESPACE)
        - --name
        - helloworld
        - --port
        - '8787'
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: rainbow-dashboard:latest
        imagePullPolicy: Never
        name: dashboard
        ports:
        - containerPort: 8787
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: rainbow-dashboard
      serviceAccountName: rainbow-dashboard
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: helloworld
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: worker-metrics
    app.kubernetes.io/instance: helloworld
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/version: 19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc0ca02
    helm.sh/chart: helloworld-0.1.0
    skaffold.dev/run-id: 60e53a48-1e82-4795-874c-36dfcc827ac5
  name: helloworld-worker-metrics
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    temporal.io/deployment-name: helloworld
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
spec:
  clusterIP: 10.96.0.1
  clusterIPs:
  - 10.96.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rainbow-dashboard
  name: rainbow-dashboard
  namespace: default
spec:
  clusterIP: 10.107.59.72
  clusterIPs:
  - 10.107.59.72
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8787
    protocol: TCP
    targetPort: http
  selector:
    app: rainbow-dashboard
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
data:
  ca.crt: '-----BEGIN CERTIFICATE-----

    MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p

    a3ViZUNBMB4XDTI2MDQwMTE2NTUyN1oXDTM2MDMzMDE2NTUyN1owFTETMBEGA1UE

    AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL3+

    QFWt8gugWXjkoDsYnyIwUEVgQRBTIAGUmKk8JAxuRCl+Z/QhkBi3WsVQ/yufu3ye

    XqKrt5yEBjaVBttichCxrLpCWjH9nmXY/KqnDdiM2+zn3u9mVIdpOIYT3t0yDmOl

    S3psb+TG80wXqnota/B3UAd2nFmkSr2lCEWYz9zxbBfStthqp8m8hoKCroh6r2Y1

    qT6+eRQnvrRMDnj6gJwVt/WNI75X4iPEVylRap+zYnw70uKzhjCvwNknElX5ExgQ

    EOjHU5yXlEwu3zVqnphGD+WpyrLx8BF1FpB7xVMK1NJGvhgrtwNrkIJMZ6ITzlLi

    eknmS+71Py70ChjW5yECAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW

    MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW

    BBTVPj3wqSU3g0qUTgvA85bx5vFUtTANBgkqhkiG9w0BAQsFAAOCAQEAMjQyFvO4

    aKyzhV83BqH+RjmpMAfvzr77CEmIk6cVFdUlwJ6wCgbgxO74LwzSOSYLZ2DS9LHy

    EYcaIKdOukBziCR/47hsVaLfZhnLlgvTw/1sOrEeVTmLcC6DEK4Wu3EQ1+3W8Wvd

    KM7VL+O5fJ1WEZh1e1ER78cTX2yt8BkO+UB6pgquNWtN/ohTFq6ju83TTawA4/2R

    vszn2DKEzAJFf+VhLIlQJb0Nr1W6qWdS7JE/4ETbcIb9xkY/wdpiI5iEoI7RN3es

    Ds7fG87+7wTIsAqCGnz0i0lb+Z23YtcV9iOuhspZpEDYDFpnPGCPSXddDBxe5iv1

    GDpvFLl/jXPEpA==

    -----END CERTIFICATE-----

    '
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  name: kube-root-ca.crt
  namespace: default
---
apiVersion: v1
data:
  release: SDRzSUFBQUFBQUFDLyt4N2EzT3FTTmYyWDdIOEhETWNKSWxXM1IvRVJJUW8yYUp5NkhlL05kVTBDR2h6dUFWVW5Kci8vbFEzb0toeFQyYnYvZTE1VWpXMWs2YVBhMTNyV3RkcW1ML2FFUXpkZHIvdHV4akgrM2lMbmZaRE80aFdjYnYvVjNzVmJOUHNUOGROY0Z5NFRydmY1aGp1cWNOME94eTNZRjc2WGE3UGNvOVBIUGZDQ2gzbXVjOHc3WWMyaHY5NmlPTmlONk9kNlI4cDJnWkpGc1JSdTkrV296U0RHTGRRSENha1UvdWhuV1l3eTlOMnYzMWE1TytITnZMaE5pTmJEdDBNT2pDRDVQZlBqclp6dDJrNU5mUElQakkzQ3c1YVl4ZUhMVHBmYXhWdlc1bnZ0aFp1bU1SYmlGdm5xVnI3ZUx0eHR5M0hEZVAyUXhzbWdYNmFlY2ZSbHVUY0F2TXNEaUU1NDBNN0t4S3lLNWdrT0VDUUx2djNReHZIYU5QdVJ6bkdEKzNNRFJNTU16ZHQ5Ly9mNlJTbnhqLys5RjJjdU52ME1Vc3cyVDg5YmR2bDA5MjdsN3phSEp2WlhOZXpwVkVBak1OeEdNUzdsY204dTN5YXlaS0dRWWh6TUI4RVVOSlRXK3J4TnEra1lDaWtscUZnZXp3TjVDSGJXODJTR0JpSGJCS3A4WVJUWTh0VW1JOUFmSGFMUVQ3amZCOUZzM3dSampJd0YzdXJPWHZScm9kNmdUaThzd09Sek9PajhTQ0h2QjRBVThtQnFXRlVDSWxkOUhMTFlQSGRPZStQUyt4SVpTeERXSU5GN0xsODZrMndnbTFKOXhHMy9NcDREcGpLRVJxOXZGcDdNOEhBdDhkNitkd1lSV0F1TUphQnZOVlFaRkNrNTFZeDRLYUYrQ0tQdFFJYTdNSXhRQWhOejVNREpwREhldytaK3M2UmxoNnhzV1dLKzBtWXNWYW9GM2FvTThDYzV0QjQyZG5HS0xjTUI0TWhHN2lmN0h2SjZZVVQ0blcxOTJlM1lEeGdDQnQ1elBhRzNuLyswLzc3NFJNY29EaUtYRVFBOUZqQThCSUttU3poVUphRW5UTWM1SG80U2gxRFAwNGlEZHVtdUVQaEtKMkU2czRPQld6eFdtSnp3Z2R4QjEwdUhPMmhEakNLMU1UbXVrL3l1RGtHN3lhOGRiQ013eDVLYjRkaG1DVjJPSHVTUitjK002NlgyNkcrZGlTOHM3MGtBNmJtQTJuRVdJdjRYUjZLRjI1Zmhub0tqTkVSekJ2ckJ3UFBKbTQwMWIxbHFIZjdJbDcwTGE0MHV6d1VhL2cra2ZIeVVLUW1oSWF3dHNmNjVzZHc3eEpYNTlBUU5zQVFHUGwxUnVkRXZJaXRJOTF6YlBNcXM1UjZoZk1hZTNLVVBjdER3YkNNQTB2YzYwaDZocVJlWVJuNzNESzBEUXIxSXlwSVdNanY5VDRVaWRoVXhSYXZZT2ROOEcxajZYMnNHYThCUFFZWTdON21GZDhlQ2o2UzhBU1ltOXd1NFZ4Qmo2blArc21jR1hibmc2ZHY4M3UrSHUzaGt2UVJ0c0RjbE5BT2NWYmIrNFNYb1ViV1hnQkRMWUNwWGZqRU1zVmt6dW5Da3RQWEtOU1paYWlISDE3c3ljUEtYeFdzUHp2cmFpZ2VIS1BIbFBBdXgwQk9GK29RSkhQWDg1STFyc09xUHZNcEpDNzIvTGt2YkZOTEVYdTFqM0t1ekRFMTFqSU95OFZJcmM4NkI0WlZZK2NDbzUvYmsyWHNzWHBscDMvWWM1UTlUK1lpdGtPS3J6c2hYYWEwMEkyeXE1Q1dDM0VKSlh5c3dqRzFUQTNMa2xvQVkwUll4clBtNHZJRW9aR3pRMkdHMFViRFNEcnNYSVBGZGpUekxGNC9PbEl2azhjS1JseVBSYUdLNWJFV1crYk1xeGtLN2VNMWFRTnpNWVVHd0JhUDE3YTA5R3pPOHZTemVUMkg2eFdRMHd0NUxPN0FlSnJLRXM0dDdzQUNDZWVnRVBjbzdFVTBGRGpNZ2JsWTJOd2h0WG1kUVlYb0V4TWdUdlZ0MG5lZkVNZ1pEVlp1aGdKbDdLa3hTcEhrKzlOWnNpVmgraEg4NDFuZmJVTm5MRVB6SGVudDZVUXBQOHdZc1NkTEJDYjZFVW1qKzltbG9xVVRWVlZadGc0Rk11YjMwTTVnTGI4UmlnWUo0UFhDTWdsTmR6MFE5Z3BaYWxCM2lEeEhlbW42aGtDUHJMY0ZwdklOalNtOW4vWm5OZWtaS3hpczZWbzNZWHlIbXRZMkorVEFVQm5pcTBWTlQxUlZqRmg3UEx0djIrSEFPNGZub1VuaFQvSlErVUdvTlh3eXIybVYyTWJmT1lYSTJFV0pMVm5xc2M1UXpJR0pLbXlDMU9hUkIwd2ZXN3hPOTR2Sy9nd2tlSlpJM0tpTVBLN3dFNGduWlVEOGlzSWU4UnZydkZiMkdhc01Da2NNTUJ6aGxocVVuUzBkZG80NXl4R3ZFVjlod0crOHMrb2lxVmcvTktucU5QOVFPRHBqeFhja1BYTG5nMkE1Vm5hQVZ6RGkxY1FKbDBHTk0za29IaDFKMzZQajJWK1R1VmhZQnJ0ZlNucGhjWHJ1U0tPSStHKzZYcDc2eUVOeGI1bjZFU3cxbHV5L2pMSEJjVHFlL3VNODZtTHdlK1k1Zm0wL3BhMzBIQXpQbUFIY2lBR0w4NW5Qdm5XV3JpbmlqMkFRTEd0YnZqbStJeTBENmo5ZXp4R25Nelh1Uzc3Uk56YnY1SnFrcDVhNWVaSmZwM3UwcjlhUjlKU294UE16UGFOMkw4UTNZS29KQ3ZXTkxBbXNiU2dFS3pzUTFERW1leWpVOTdhRTE1WTVyYkNwWWNUaEFoZ3pqOFl6aDBOb3FENk51VUFNYlY2KzVrOFNzMldjU1kzelNpeDJwTkhHTWpXL1BvYzhKUHdwN0J5cHRGMFREM1R0a2I0bmNndk1DYzd4VVpaR3VSMzJtSm8vS0ljWW96VWNpaHRnaXFuTmJ5aC9FRjRoY2dwSnZRM05EN3ptbzBnN2x0Z2IxRGJhMjFKUHNBMDlkNGJDMWlHMkNBWHNTUHF4bElaYVFtTFZrVVlacXFVU2thQ0ZvTnNoN2hJc3k3VS96angzNGlWSEdpVTJxUjR1ejVTVnZMeDhraVhXaDBhMytjeVRKWnlSdkhVVGsySFpQb2tVaktUZUVacmFEa1UwSnArdStPMVM5ZFBVZlR2L2NxeW45a2pjRVQrN3R4eFp6N0YzakVPNmxIb3BORlFxWTRDa2g1YXBwODV3RU13TjhHSHoyb3prUmNyNXdSbm45WDhvMUgyYVEwMzFTTGpBQ3BkUFRSK1VlL0laWnl5T2dUbTdmVWJtcUtUcXgrdWdPeDFjemc4TWdUdGo2Uk1iajdUUlFoZS9MVGVqcWNscTRwTEpWa3RkSCtuTDVmdjFPdkpRNUNpZkxVNnllQTZNQTdaTUZVODIxN3pkdXl2NVpTKytJNGRDTjlzR0tPMms3bllYSVBkV0V5MkFxWERRT09zWVlQcDdtMWN4cW5pZTJKQm9BU2pwTENwRVVvNFUwRkNQbEdmRzRnNFNQd3pKR0lXUlh6ZjdqOFVna2FWZUxrdWoxQjRRTFZTWFFnSUd3MGJNUzcwTm1jOHlCQjl3aEJzVWdld0JtdE5HTGo2WVZSNStLMk1OWjhUdkV5OWVEd1BTejhjMGwwY2F6V0ZrM2xwUHlKTHVXNXpuT1hVMVRmam43VUxqUktnUTl6YW5IZVd4a3ppUzkwVG1QUEhJV1Q5dEx0WTJLaisvSGhpSG0yVmx6dSsreXdYSmNWZWxIcWV3MERoc0pnYmVmQVNERnl2U0UxdlNGTzIxK3k0VG5UZ3F6OXVvWG8vVS83eDJwUFliVXA0a3RzL2tzYnFUUnlSWEUwN3pzV05PdmZjeFNLejUyWWNMbzVmVE9BMDJuc1dOY25JZXhLbUZaWXBZbG5TU253WEtsOE91cDVVY3RyZTVtUWNNTm5IR1U0LzRHWVY0VFh4dkdVNUUrTmZoTUFPSFl2bWNkM0paT3VkNWkvaDM2QWVPZ1ZQd2h0L2U1Nkx2MEZKTFlSMXBtZEk5ajBXTUF2WTBSaVk1alZjd3lVdmwzNzZQeGlLMm82a0hqZTRWM3JydnBMUTUzWWlzWTg5WnY3MUREdWZnTlQ3YmJmYnZ5K1NKV2VzVzlvVHAzMWM2aTRrZHFxbGphRmdlS2pFd2lIWW42eDAyay9EZ1c2R2Vva0wySmdIUmZrSmloeHF0TDlSRzNyNTNFMkp4UFJJYk9jSGl4em1IWmlmZjdaTWprdlIxeVZFVVd5blJteFdlVG40b2ZYdVJRMHR0L1BVWXBQTi9Gb05FTjVUOFFmSm5lZDZTRTVvWUZCTm5lSXIvSTUxdnJCTHR1M2FrWGxGemJMTWtKZWUvektIc2w2NURLSitmL0hPUkQ3RXpWaEtMUDJ1d0UvY3ZCc0taKzBYR01wVUltTnFNOE54SE1CQ21yNXQ5cFc5ZTdUSEoyWG94MXdkUHN1Ump5OUJTa244K2kxa2c0YVBGbGJkb3BPWURFdWFnUWNycGZha2RHcnhhYXF1cFIzV2VwRlBmV0ViWHM2V2VENFpzWUJrSDN3NVZXc05ZaGxyWVBGbFRpNEhCZU8rU2dJR2hFYzZsZWdsSmVqRXhxZDJQRnErUW1qRUh4WVpxZFZKM0lsN0RhSU5uSDRINFFiaTZ2RFg3L3cvdEhjUzVtN2I3ZjdXREVIb3UrU1hKTWY0VzR3QVZKSW1zMURqN3RuVlROOHJhRCsydG04UnBrTVhiNHZyaU9JTmV1OSttZVNsci8vM1Ezc1lZeHptOWMwNnpMY3hjand6NXRvMjlyWnVtd2M0bG5iTHE0cGowZ281RG5wUzMzREFKM3QyQ05HL0lQNlNweW43ME52dDBzNmRXalEvdE1NUHAzRVZiTnp1M2tTRnBBbEU1N3UrSGRvcDhONlJYZ05UMjhnWnhhZ3dNMXBmWHNTZUhSRGNNbmlaRjc3K0k2K1VUVTEwVGJyYm13ZzZGYUFmR2lnK2lXVFo5UmJ2VHVFSk9LVTRpVFVEU01pQjYyK2FVLzlLWURFaXRPUWpRV05rUi96Z1N4cWlRbitSeFd1RlJxWFJScysySGMxWFB4Y0xtUll3aUxRSG1OQ0R4Y2FGekxqWGQ3ZlBoSUhER2VFL1hIU3FrdmlJWUN5WlhXa2dPaVU1WEMyaUtKWmNURzIwb0YvalFFSWpPci9ZdkZvRGtSUTR6TnE4SWNsTS9qWm4wY20rYUQ0cXI4NWEyWUVpOVF0ZUlTQzFKOEN1bjEvc0drazd3blpSMWU1ZmFhTmJReHJVZWxjZDBuV1pkMWJzOG4zS3BSZGV4NSs2dnp0L3dBNmxib1NGRUYzNG81OEYycEdka3ZGRW9vajEyZk5lY0JwUGhJRmlFaEE5bCt2dU50c1hNTDV4TlpHMko4a201OTB0N24vYTNtamN4bzJCazZtV2RWdTcxMG1mQnZ2S040alRzRkZpR3RvRzBOaEo4ZTNTRHU5QXlEa2RRNWJUemVrcERZLzFtYkYvY2QveGVIRFh2NzVvNjRZZDQvdXcxd2M5amFRTk1kWTFDdkM5cllScWY1WnhTTDVRbHZRdE5sYUZqNzcxU0NFZ3NxanZIVk5aZ1BvaHR2b3hkeTlnblB6N0hhQU5vWFR2OXZYeUJ6L3NrK1I5RmdQQ0dEeVN0b0RsMDZCZkFITEhRVkVndVMwQWdmbmFIbHFCQ0pQTXc3bndUTlBkMmdmSGhJUGprV3ZzMzgxOTVWVzV6bGtkeVBqa1RYV3RJOTgxWUJzNnBmeVIydVJoTlBZdWp2Ri9kYitpLy9iejFhNGQvd3R5bnNWWmlqdmdpb2RnSlIrbnlPbGRKcElaWDhZMXQvaWxPeTduenUvSHc5Vmo5ZFYrOGpXYnp1VWhmN2J5UEd6eEk3eDAvaVYrcWEvVU1qVFhoZlM3ZjFQVlhQcWoybDJIM1V6NzZGM2k3endGdmxxbjVza1RXRUJNN1VoTWdMY3N6Tjg2R3FsZEU4czM5aGRpN3RPbmwzK2M3bG9zY0dhQlFQemdHdmFjai9yVXZ1ZmNuOGtUVGJ1RW9kNWU5a09haUpqWnUrWHlQd3Q0ZW1Bb0REZjE0QjB2QnhiMzk1bTdjL3dzdXJ2akV3UG1DYUhaZWk4bmEwOWsvMi9ZMlZtNXk3eWN4cnpqMzQveVd2MjU5YytidnlSMGVOR2YzK2YrV083NFUzL1dyMkMvWitqNEgvUWh2UzNvZVNEZ09NN2V4ZU9XUDI5aFVHbndyUDhtak5EaS9ocGJUNWhtdTdIT2F4N3pWTjZmM2RWZDRiTWI1emdvVGJQR3o0Q0ttN3RZQzFmUHorNUZmeUZ0NjdoaE1hVU5NNmxPSDVscG9Ba3gxM21hVTJtOGpac0VKUkVNUkc2aVdJWkFhTlREblg5SWs4OVA1Rys5OWZsS0hOdDd2L0lMMkpQL1dtTDVlby9aUGRlZDl4dCtGVHEzaklUaS9lNktmS0ZSNytscWVIRWJNZjlvUDdWV0FTVkVkNVJpWDVlb3E4SDViamMzMlhOUjlRYzgydjNxMm41NkYxUk95SVdkemFQV011bDJlZStGWDNJdkQyTSs5THVveHpPcUY2VEwyOHpPUEVJTWd3L1Yrc1RxSFNTZUt0NW52d2pUcnNJOXduejdDSkhpc096OEdjZitaNC9sUGluaVlCQjN5MjBQekpwdU02ZFJQZnJLMi8yOGVvRTJhd1czV1NYMlkrbnVZZGJBTHQxRVFlWStIWjY3SWFmVWZ3aWhZdVdsV2JxWDYrcXpmMnJIZm8wMFFPZjNXdkx4SC94N1ZYOG4xdjBldEZvYTJpMVA2YTZzRmsrUnhrOXZ1Tm5Jek4zME00ajlRSENaeDVFWlp2L3JtclZOZHk5OGJFRVJwQmlQazlodWZ5OTNyRzhJSWVxN1RzWXMrL2ZEdVhqOWlqYS9NdDZzUC9Zc2dLdWYzWFJ3K3B2NGY5R3ZBNXZJZCt2RmcyU25kd05VcXhzNmo0KzcrMk9aUkozRDZyU2ZHRlhqWWZlbXc3Z3ZYNlQ3M2hNN0xjeGQxK0NkbmhkQUw5d3lSUUlaZm42dHphK0lURVBvdHgxM0JIR2Zmb3pSeEVYVVl3bm1hdVZ2NVc3K2x4cEZMbXBKNG05WGU3RlFMWEhpczdOSnY5WmdlVTdka2NPdTUyYmVMOXRURkxzcmliVFZYSXdBYTM2bDBiajNUNlhTK1IwMEFOa2Z1V0lnVEg1NGdXWDlhT1R5RnhiOUQ1Lzhxc0gyMnNSL0NvMlNva2xvMGQxVlpjZU1XL1ZaRlNXVkxPZkUxWFpGbmZweFdzUGdpTC82ay93MksrOWNUcnY0UEJiOFBCVlV5ckt6bndjenQxM0ZQNkdhRjQvMmlTTngrU3lzN1NqQnpLMjdMM0NROWRlNjBFcGluN211K3BaOHQ5MXM4YzZLVVZtc0x3K1NidTBWdWxFSFA3YmM0NGVmR0NjelBqWHNXNmoyWCtiN2ZhcVI3eW1kNWxMcTFGY3B2emw5ZERJdCtTNmhBa0NLSVhTZmVSMVY3dFY3OVFyb2FlZ0ZNaW9rb2lqTzZ4Yk90eUFxbmIva3VBWk1Gb1p0bU1FejZyZTl0OXZuNTZlV1pFM2p1ZTd2YVJPMDI4b1BpS0lOQjVHNmJNM2RhYnJSci9OMWsrc1hiOU51SE5wajh1UmpNMy8rY0xkK1diNWNkV3kzNlN1U0Vreit1RVY3K1VDWFhSRm4vVjJYWnplemZUaHF4MzJwS3hHYkhLbjNCSUdxMmJsM29CSkdicHQrMnNlMWVXY0xQc2tRNitmbjhVeWE5RithRjRxdk1zeDlKMDJ0bmFYYm15cy9EN1p3TjFYUGdmVUdsTmY3L0EvWlM0bFhlYVAvOVB3RUFBUC8vTUt6clBKSXhBQUE9
kind: Secret
metadata:
  labels:
    modifiedAt: '1776872533'
    name: helloworld
    owner: helm
    version: '1'
  name: sh.helm.release.v1.helloworld.v1
  namespace: default
type: helm.sh/release.v1
---
apiVersion: v1
data:
  api-key: ZXlKaGJHY2lPaUpGVXpJMU5pSXNJbXRwWkNJNklsZDJkSGRoUVNKOS5leUpoWTJOdmRXNTBYMmxrSWpvaWVEY3llWFVpTENKaGRXUWlPbHNpZEdWdGNHOXlZV3d1YVc4aVhTd2laWGh3SWpveE9ETTVNVGMzTkRZMExDSnBjM01pT2lKMFpXMXdiM0poYkM1cGJ5SXNJbXAwYVNJNklqQlBOak5QWjBkNWJtTTNWRkJpZEZGbGIzUXlkR3QzZDNkMmFqUmFZVGhwSWl3aWEyVjVYMmxrSWpvaU1FODJNMDluUjNsdVl6ZFVVR0owVVdWdmRESjBhM2QzZDNacU5GcGhPR2tpTENKemRXSWlPaUkzTkRrMVpESTVPR00wTmpnMFpXSm1Zamd5TVRBd01Ua3pZMlEwWXpFMk5pSjkuY0tYdzdZOWhzX3JXei1LNnBpaWdQLVZZN19Qc19DTFQxRWdTd2lyUkVQYTBjNUJjckt2ZjFyZ1pqYUlpanM5R3pZU2dDd3c5N2hwS3RlTWtzRTVLRFE=
kind: Secret
metadata:
  name: temporal-api-key
  namespace: default
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rainbow-dashboard
  namespace: default
---
apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  annotations:
    meta.helm.sh/release-name: helloworld
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: helloworld
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/version: 19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc0ca02
    helm.sh/chart: helloworld-0.1.0
  name: helloworld
  namespace: default
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  rollout:
    gate:
      workflowType: RolloutGate
    steps:
    - pauseDuration: 30s
      rampPercentage: 25
    - pauseDuration: 30s
      rampPercentage: 50
    - pauseDuration: 30s
      rampPercentage: 75
    strategy: Progressive
  sunset:
    deleteDelay: 5m
    scaledownDelay: 30s
  template:
    metadata:
      annotations:
        deployment.kubernetes.io/timestamp: '1776872532'
    spec:
      containers:
      - env:
        - name: TEMPORAL_TASK_QUEUE
          value: default/helloworld
        image: helloworld:19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc0ca029
        imagePullPolicy: IfNotPresent
        name: main
        readinessProbe:
          httpGet:
            port: 8080
  workerOptions:
    connectionRef:
      name: helloworld
    temporalNamespace: quickstart-shashwat-learning.x72yu
---
apiVersion: temporal.io/v1alpha1
kind: TemporalConnection
metadata:
  annotations:
    meta.helm.sh/release-name: helloworld
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: helloworld
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/version: 19ec48c7b3f7b675f6cba2b2cf7c443283f28d0b794c900f8040b773cc0ca02
    helm.sh/chart: helloworld-0.1.0
  name: helloworld
  namespace: default
spec:
  apiKeySecretRef:
    key: api-key
    name: temporal-api-key
  hostPort: ap-northeast-1.aws.api.temporal.io:7233
