{{- if not .Values.temporal.connectionName }}
apiVersion: temporal.io/v1alpha1
kind: TemporalConnection
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  hostPort: "{{ .Values.temporal.address }}"
  {{- $apiSecretName := .Values.temporal.apiKey.name | trim }}
  {{- $apiSecretKey := .Values.temporal.apiKey.key | trim }}
  {{- $mtlsName := .Values.temporal.mtlsSecretName | default "" | trim | trimAll "\"" }}
  {{- if $apiSecretName }}
  apiKeySecretRef:
    name: {{ $apiSecretName | quote }}
    key: {{ $apiSecretKey | quote }}
  mutualTLSSecretRef: null
  {{- else if $mtlsName }}
  mutualTLSSecretRef:
    name: {{ $mtlsName | quote }}
  apiKeySecretRef: null
  {{- end }}
{{- end }}