image:
  repository: rainbow-release-job
  tag: latest
  pullPolicy: Always

aws:
  roleArn: ""
  region: us-east-2

release:
  name: helloworld
  ecrRepo: 025066239481.dkr.ecr.us-east-2.amazonaws.com/helloworld
  sourceTag: latest
  intervalSeconds: "30"

traffic:
  intervalSeconds: "3"
  workflowType: HelloWorld
  workflowsPerRun: "6"

cleanup:
  intervalSeconds: "30"

temporal:
  address: ""
  namespace: ""
  taskQueue: ""
  workerDeployment: ""
  apiKey:
    secretName: temporal-api-key
    secretKey: api-key
